### ISSUE TITLE
Icons only shown as symbols.

### ISSUE THREAD

**Issue by TheRadioDept** [SylEleuth/gruvbox-plus-icon-pack#2] opened 2023-04-05 16:08 UTC
Hello. 

I am sorry if it's a stupid question, but my icons are only shown as symbols.
![image](https://user-images.githubusercontent.com/58568149/230139346-430b6a4c-0200-42f3-833a-65eafa1cc91c.png)

It was looking as it should when I just installed them, but after I rebooted my system, it changed to this format.

Is there any way I can make them look like they used to be?

**Comment by SylEleuth** [comment] 2023-04-05 20:33
Can You please confirm that icon pack is properly installed and icons are actually "working"? For example they are show up in dashboard application and they are in the same style (You can look into apps/scalable folder for a comparison)? Because some of those icons in a screenshot are similar to the pack (like file browser, terminal), but others are not (like firefox or telegram). And the color for symbols is off. Can You use different icon pack and reproduce the same error? What if you load other packs and at the end come back to the Gruvbox Plus?

**Comment by SylEleuth** [comment] 2023-04-24 12:09
Not enough info. Closing for now.

**Closed by SylEleuth** 2023-04-24 12:09 UTC
